
version: '3'

services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: blog
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - db

volumes:
  pgdata:
