version: '2'

services:
  db:
    image: postgres
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - prod.env
    size: s2
  web:
    image: chengyu0316/myblog_v2:latest
    restart: on-failure
    depends_on:
      - db
    links:
      - db:db
    env_file:
      - prod.env
    size: s3
  proxy:
    image: chengyu0316/caddy:latest
    restart: on-failure
    env_file:
      - prod.env
    volumes:
      - caddydata:/root/.caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    links:
      - web:web
    size: s2
    fip: 209.177.88.14
