apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  tls:
  - hosts:
    - yucheng.life
    secretName: pw-secret
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: pw-lb
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pw-lb
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pw-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pw-nginx
spec:
  selector:
    matchLabels:
      app: pw-nginx
  replicas: 4
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: pw-nginx
    spec:
      containers:
        - image: chengyu0316/myblog_v2_nginx
          imagePullPolicy: Always
          name: nginx-server
          ports:
            - containerPort: 80
